server.port=8080
spring.application.name=springBoot-mybatis-demo

#ָ������Դ������,������������Ӧmysql8.x
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#mysql���ݿ��û���
spring.datasource.username=root
#mysql���ݿ��û�����Ӧ������
spring.datasource.password=root
#ָ������url,������test���ݿ�
spring.datasource.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true

#�������ͱ�����·��
mybatis.type-aliases-package=com.fly.entity
#����mapperӳ���ļ�·��
mybatis.mapper-locations=classpath:mapper/**/*Mapper.xml
#����ָ��mybatis�����ļ�
#mybatis.config-location=

#�Ƿ����û���
mybatis.configuration.cache-enabled=true